### ISSUE TITLE
Error with the descriptor resources when using fast-jar

### ISSUE THREAD

**Issue by ia3andy** [quarkusio/code.quarkus.io#428]
**Describe the bug**
```
Caused by: java.io.IOException: Failed to locate codestarts/quarkus on the classpath
        at io.quarkus.platform.descriptor.loader.json.ClassPathResourceLoader.loadResourceAsPath(ClassPathResourceLoader.java:26)
        at io.quarkus.platform.descriptor.loader.json.impl.QuarkusJsonPlatformDescriptor.loadResourceAsPath(QuarkusJsonPlatformDescriptor.java:144)
        at io.quarkus.devtools.codestarts.QuarkusPlatformCodestartResourceLoader.loadResourceAsPath(QuarkusPlatformCodestartResourceLoader.java:19)
        at io.quarkus.devtools.codestarts.CodestartCatalogLoader.loadCodestarts(CodestartCatalogLoader.java:63)
        at io.quarkus.devtools.codestarts.CodestartCatalogLoader.loadCodestarts(CodestartCatalogLoader.java:51)
        at io.quarkus.devtools.codestarts.quarkus.QuarkusCodestartCatalog.fromQuarkusPlatformDescriptor(QuarkusCodestartCatalog.java:64)
        at io.quarkus.devtools.commands.handlers.CreateProjectCommandHandler.execute(CreateProjectCommandHandler.java:107)

```

It seems something is wrong with the resources names.

**Comment by ia3andy** [comment]
To reproduce, use fast-jar, run the jar and create an application in the UI.

**Comment by maxandersen** [comment]
create an application in which UI ?

**Comment by ia3andy** [comment]
```
mvn clean install -DskipTests 
java -jar target/quarkus-app/quarkus-run.jar 
__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
2021-02-17 13:35:31,502 INFO  [io.qua.cod.ser.QuarkusExtensionCatalogService] (main) Extensions Catalog has been processed with 392 extensions:
    Quarkus platform: io.quarkus:quarkus-universe-bom:1.11.3.Final
    tagsFrom: Optional.empty
2021-02-17 13:35:31,665 INFO  [io.qua.cod.res.GitHubResource] (main) GitHub is disabled
2021-02-17 13:35:31,666 INFO  [io.qua.cod.ser.GoogleAnalyticsService] (main) GoogleAnalytics is disabled
2021-02-17 13:35:31,668 INFO  [io.qua.cod.res.CodeQuarkusResource] (main) Code Quarkus is started with:
    environment = dev
    sentryDSN = null
    quarkusVersion = 1.11.3.Final,
    gitCommitId: local,
    features: []
2021-02-17 13:35:31,773 ERROR [io.qua.run.Application] (main) Port 8080 seems to be in use by another process. Quarkus may already be running or the port is used by another application.
2021-02-17 13:35:31,773 INFO  [io.qua.run.Application] (main) Use 'netstat -anop | grep 8080' to identify the process occupying the port.
2021-02-17 13:35:31,773 INFO  [io.qua.run.Application] (main) You can try to kill it with 'kill -9 <pid>'.
~/w/r/q/code.quarkus.io> java -jar target/quarkus-app/quarkus-run.jar                                                                                              1 master!
__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
2021-02-17 13:36:24,190 INFO  [io.qua.cod.ser.QuarkusExtensionCatalogService] (main) Extensions Catalog has been processed with 392 extensions:
    Quarkus platform: io.quarkus:quarkus-universe-bom:1.11.3.Final
    tagsFrom: Optional.empty
2021-02-17 13:36:24,342 INFO  [io.qua.cod.res.GitHubResource] (main) GitHub is disabled
2021-02-17 13:36:24,343 INFO  [io.qua.cod.ser.GoogleAnalyticsService] (main) GoogleAnalytics is disabled
2021-02-17 13:36:24,345 INFO  [io.qua.cod.res.CodeQuarkusResource] (main) Code Quarkus is started with:
    environment = dev
    sentryDSN = null
    quarkusVersion = 1.11.3.Final,
    gitCommitId: local,
    features: []
2021-02-17 13:36:24,442 INFO  [io.quarkus] (main) code.quarkus.io 1.0.0 on JVM (powered by Quarkus 1.11.3.Final) started in 1.385s. Listening on: http://0.0.0.0:8080
2021-02-17 13:36:24,443 INFO  [io.quarkus] (main) Profile prod activated. 
2021-02-17 13:36:24,444 INFO  [io.quarkus] (main) Installed features: [cdi, hibernate-validator, jgit, kotlin, rest-client, resteasy, resteasy-jsonb, sentry, servlet, smallrye-health, smallrye-metrics, smallrye-openapi]

```


the UI is there (obviously ✌️): http://0.0.0.0:8080

**Comment by maxandersen** [comment]
ah - i missed the notification was on code.quarkus :)

**Comment by maxandersen** [comment]
Not stale

**Comment by aloubyansky** [comment]
This should be fixed actually.

**Comment by ia3andy** [comment]
I think it's already fixed, we are now using fast-jar..

**Comment by aloubyansky** [comment]
Looks like I don't have permissions to close issues here.
